os: osx

osx_image: xcode12.5

language: objective-c

# cache: cocoapods

# podfile: Example/Podfile

# before_install:

# - gem install cocoapods # Since Travis is not always on latest version

# - pod install --project-directory=Example

jobs:

  include:

    - name: Test

      script:

        - set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/YiVideoEditor.xcworkspace -scheme YiVideoEditor-Example -destination 'platform=iOS Simulator,name=iPhone 12 Pro Max,OS=14.5' ONLY_ACTIVE_ARCH=NO | xcpretty

    - name: Lint

      script:

        - pod lib lint

